[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "fhvite"
dynamic = ["version"]
description = "Vite plugin for FastHTML/MonsterUI that automates installation & building"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Curtis Allan", email = "ca@answer.ai"}]
keywords = ['nbdev', 'jupyter', 'notebook', 'python']
classifiers = ["Natural Language :: English", "Intended Audience :: Developers", "Development Status :: 3 - Alpha", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only"]
dependencies = ['fastcore', 'python-fasthtml', 'pybun']

[project.urls]
Repository = "https://github.com/AnswerDotAI/fhvite"
Documentation = "https://AnswerDotAI.github.io/fhvite"

[project.entry-points.nbdev]
fhvite = "fhvite._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "fhvite.__version__"}

[tool.setuptools.packages.find]
include = ["fhvite"]

[tool.nbdev]
custom_sidebar = false
