# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fhvite',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/fhvite',
                'lib_path': 'fhvite'},
  'syms': {'fhvite.core': {'fhvite.core.foo': ('core.html#foo', 'fhvite/core.py')}}}
